# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a9a3fff5a778d1add9fdea4aebd182f90244dcbe67187971dffd2e8d6fe39c3e8d5b8e8bcb254b03f23714d2525d7ca176a2af6143a3c6440121fcb4747ed82a

test:
  secret_key_base: 9de4b5fed705c11389abf8be117f4b5a619c52af7a252125e3c9451e8aa28d31ccc8a5c2a7ee0ade29494cde22ce13b108a5720b1a03c09bb240895d2b7aa05b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
